### ISSUE TITLE
Relationship distribution

### ISSUE THREAD

**Issue by Btibert3** [graphaware/neo4j-graphgen-procedure#1]
I think the ability to generate a random number of relationships between two nodes is fantastic, but I am not sure if it's working the way I had expected. I am on `3.0` and have just two additional plugins loaded, this, as well as `apoc`.
## 1.  Clean database

```
MATCH (n)
OPTIONAL MATCH (n)-[r]-()
DELETE n,r
```
## 2.  Run the example

```
CALL generate.nodes('Person', '{name: fullName}', 10) YIELD nodes as persons
CALL generate.nodes('Skill', '{name: word}', 20) YIELD nodes as skills
CALL generate.relationships(persons, skills, 'HAS_SKILL', '{since: unixTime}', 10, '3-7')
YIELD relationships as relationships RETURN *
```
## 3.  Look at the distribution.

I was expecting to see some distribution between 3-7, since each person will be connected to each of the 20 `Skill` nodes between 3-7 times.

```
MATCH (n:Person)
OPTIONAL MATCH (n)-[r]->(s:Skill)
WITH n, COUNT(r) as skills
RETURN skills, COUNT(DISTINCT(n)) as peeps
ORDER BY skills
```

returns

```
╒══════╤═════╕
│skills│peeps│
╞══════╪═════╡
│5     │10   │
└──────┴─────┘
```

**Comment by ikwattro** [comment]
Hi @Btibert3 

Thanks for testing.

Actually, with your call, each person will be connected to "between 3 and 7" skills.

``` java
@Test
    public void testRelationshipDistributionRight() {
        int personsCount = 0;
        executeCypher("CALL generate.nodes('Person', '{name: fullName}', 10) YIELD nodes as persons " +
                "CALL generate.nodes('Skill', '{name: word}', 20) YIELD nodes as skills " +
                "CALL generate.relationships(persons, skills, 'HAS_SKILL', '{since: unixTime}', 10, '3-7') " +
                "YIELD relationships as relationships RETURN *");


        try (Transaction tx = getDatabase().beginTx()) {
            Iterator<Node> persons = getDatabase().findNodes(Label.label("Person"));
            while (persons.hasNext()) {
                Node person = persons.next();
                ++personsCount;
                int skillsDegree = person.getDegree(RelationshipType.withName("HAS_SKILL"), Direction.OUTGOING);
                assertTrue(skillsDegree <= 7 && skillsDegree >= 3);
            }

            tx.success();
        }

        assertEquals(10, personsCount);
    }
```

**Comment by Btibert3** [comment]
That is what I was expecting, and perhaps my query above is wrong, but all 10 people (`peeps`) had 5 skills, there was no variance.  I tried this on other datasets (larger `N`s) and replicated the constant relationship count. 

I was looking to get more of a distribution, say, 3 had 5 skills, 4 had 2 skills, 1 had 7 skills, 2 had 6 skills, etc.

**Comment by ikwattro** [comment]
Ok ok, normally it should random it a bit. Let me look further

**Comment by ikwattro** [comment]
Can you pull latest commits and re-compile, this should be ok now

**Comment by Btibert3** [comment]
Absolutely.  I don't have my macbook with me at work, but i will run later on today.  Thanks.

**Comment by Btibert3** [comment]
Hazaaa!  This is what I got running the same 3 snippets above

```
╒══════╤═════╕
│skills│peeps│
╞══════╪═════╡
│3     │6    │
├──────┼─────┤
│4     │2    │
├──────┼─────┤
│5     │1    │
├──────┼─────┤
│6     │1    │
└──────┴─────┘
```

Fantastic, thanks!

**Comment by ikwattro** [comment]
Cool !
