### ISSUE TITLE
Yaml issue

### ISSUE THREAD

**Issue by graphadvantage** [graphaware/neo4j-graphgen-procedure#2]
Hi

I'm running Community 3.0.3, zip installed.  I have graphaware UUID, TimeTree, Framework running, working fine.

I keep getting this error:

CALL generate.nodes('Person', '{name: fullName}', 10) YIELD nodes as persons RETURN persons

Failed to invoke procedure `generate.nodes`: Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/yaml/snakeyaml/Yaml

I've also tried compiling with versions 2.5.4, 2.7.3 & 2.7.5, all tests pass.

Thanks

Michael

$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.graphaware.neo4j:graphaware-graphgen-procedure:jar:1.0-ALPHA
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 112, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ line 119, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building graphaware-graphgen-with-dependencies 1.0-ALPHA
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.7.3/jackson-dataformat-yaml-2.7.3.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.7.3/jackson-dataformat-yaml-2.7.3.pom (8 KB at 9.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.7.3/jackson-core-2.7.3.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.7.3/jackson-core-2.7.3.pom (5 KB at 64.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.7.3/jackson-dataformat-yaml-2.7.3.jar
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.7.3/jackson-core-2.7.3.jar
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.7.3/jackson-dataformat-yaml-2.7.3.jar (314 KB at 1346.3 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.7.3/jackson-core-2.7.3.jar (247 KB at 871.4 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ graphaware-graphgen-procedure ---
[INFO] Deleting /Users/ecoreefs/neo4j-graphgen-procedure-master/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ graphaware-graphgen-procedure ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/ecoreefs/neo4j-graphgen-procedure-master/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ graphaware-graphgen-procedure ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 19 source files to /Users/ecoreefs/neo4j-graphgen-procedure-master/target/classes
[WARNING] /Users/ecoreefs/neo4j-graphgen-procedure-master/src/main/java/com/graphaware/neo4j/graphgen/YamlParser.java: /Users/ecoreefs/neo4j-graphgen-procedure-master/src/main/java/com/graphaware/neo4j/graphgen/YamlParser.java uses unchecked or unsafe operations.
[WARNING] /Users/ecoreefs/neo4j-graphgen-procedure-master/src/main/java/com/graphaware/neo4j/graphgen/YamlParser.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ graphaware-graphgen-procedure ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/ecoreefs/neo4j-graphgen-procedure-master/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ graphaware-graphgen-procedure ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 10 source files to /Users/ecoreefs/neo4j-graphgen-procedure-master/target/test-classes
[WARNING] /Users/ecoreefs/neo4j-graphgen-procedure-master/src/test/java/generate/RelationshipProcedureTest.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/ecoreefs/neo4j-graphgen-procedure-master/src/test/java/generate/RelationshipProcedureTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ graphaware-graphgen-procedure ---
[INFO] Surefire report directory: /Users/ecoreefs/neo4j-graphgen-procedure-master/target/surefire-reports

---
##  T E S T S

Running com.graphaware.neo4j.graphgen.faker.FakeServiceTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.781 sec
Running com.graphaware.neo4j.graphgen.util.CountSyntaxUtilTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec
Running generate.Integration.GeoIntegrationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.057 sec
Running generate.Integration.UseCasesIntegrationTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.468 sec
Running generate.LinkedListProcedureTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.404 sec
Running generate.NodeProcedureTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.367 sec
Running generate.RelationshipDistributionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.437 sec
Running generate.RelationshipProcedureTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.546 sec
Running generate.ValueProcedureTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.23 sec

Results :

Tests run: 28, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ graphaware-graphgen-procedure ---
[INFO] Building jar: /Users/ecoreefs/neo4j-graphgen-procedure-master/target/graphaware-graphgen-procedure-1.0-ALPHA.jar
[INFO] 
[INFO] --- maven-shade-plugin:2.4.3:shade (default) @ graphaware-graphgen-procedure ---
[INFO] Including com.github.javafaker:javafaker:jar:0.8 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including org.yaml:snakeyaml:jar:1.13 in the shaded jar.
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /Users/ecoreefs/neo4j-graphgen-procedure-master/target/graphaware-graphgen-procedure-1.0-ALPHA.jar with /Users/ecoreefs/neo4j-graphgen-procedure-master/target/graphaware-graphgen-procedure-1.0-ALPHA-shaded.jar
[INFO] Dependency-reduced POM written at: /Users/ecoreefs/neo4j-graphgen-procedure-master/dependency-reduced-pom.xml
[INFO] Dependency-reduced POM written at: /Users/ecoreefs/neo4j-graphgen-procedure-master/dependency-reduced-pom.xml
[INFO] Dependency-reduced POM written at: /Users/ecoreefs/neo4j-graphgen-procedure-master/dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.921 s
[INFO] Finished at: 2016-06-29T12:30:31-07:00
[INFO] Final Memory: 35M/315M
[INFO] ------------------------------------------------------------------------

**Comment by ikwattro** [comment]
Hey @qosmy-michael , thanks for the report. It is due to a last change where the yaml dependency was set to provided. I have just pushed a revert.

Can you pull the latest commit and recompile.

Please let me know if this fixes your issue.

Thanks

Chris

**Comment by graphadvantage** [comment]
All good! Thanks!
